Testing: main

main:
	g++ -g -o testing -std=c++11 main.cpp ../Header/Shape.cpp ../Header/Data.cpp ../Header/Tensor.cpp ../Header/Operator.cpp ../Header/Objective.cpp ../Header/Optimizer.cpp ../Header/Layer.cpp ../Header/NeuralNetwork.cpp -lcudart -lcudnn
