#include "LossFunction/CrossEntropy.hpp"
#include "LossFunction/HingeLoss.hpp"
#include "LossFunction/MSE.hpp"
#include "LossFunction/SoftmaxCrossEntropy.hpp"

#include "LossFunction/BEGANDiscriminatorLoss.hpp"
#include "LossFunction/BEGANGeneratorLoss.hpp"
#include "LossFunction/VanillaGANDiscriminatorLoss.hpp"
#include "LossFunction/VanillaGANGeneratorLoss.hpp"
#include "LossFunction/WGANDiscriminatorLoss.hpp"
#include "LossFunction/WGANGeneratorLoss.hpp"
