#include "Module/LinearLayer.h"
#include "Module/ConvoulutionLayer.h"
// #include "Module/BatchNormalizeLayer.h"
// #include "Module/CUDNNBatchNormalizeLayer.h"
#include "Module/PReluLayer.h"
#include "Module/TransposedConvoulutionLayer.h"
